EPL_sofascore = {"Arsenal Football Club": "Arsenal", "Aston Villa Football Club": "Aston Villa",
                 'Barnsley FC': 'Barnsley',
        'Blackburn Rovers Football Club': 'Blackburn Rovers',
                 'Blackpool FC': 'Blackpool',
                 'Birmingham City Football Club': 'Birmingham City',
       "Athletic Football Club Bournemouth": "AFC Bournemouth", "Brentford Football Club": "Brentford",
       "Brighton & Hove Albion Football Club": "Brighton & Hove Albion",
                 'Bristol City Football Club': 'Bristol City',
                 "Burnley Football Club": "Burnley",
       "Cardiff City Football Club": "Cardiff City",
        'Charlton Athletic FC': 'Charlton Athletic',
       "Chelsea Football Club": "Chelsea",
                 'Coventry City FC': 'Coventry City',
                 "Crystal Palace Football Club": "Crystal Palace",
                 'Derby County Football Club': 'Derby County',
       "Everton Football Club": "Everton", "Fulham Football Club": "Fulham", "Leeds United Football Club": "Leeds "
                                                                                                           "United",
    "Huddersfield Town Association Football Club": "Huddersfield Town",
       "Hull City FC": "Hull City",
       "Leicester City Football Club": "Leicester City", "Liverpool Football Club": "Liverpool",
        'Luton Town FC': 'Luton Town',
       "Manchester City Football Club": "Manchester City", "Manchester United Football Club": "Manchester United",
    'Millwall Football Club': 'Millwall',
       "Middlesbrough Football Club": "Middlesbrough",
       "Newcastle United Football Club": "Newcastle United", "Norwich City Football Club": "Norwich City",
       "Nottingham Forest Football Club": 'Nottingham Forest',
                 'Peterborough United FC': 'Peterborough United',
        'Preston North End Football Club': 'Preston North End',
                 'Reading Football Club': 'Reading',
                 'Rotherham United Football Club': 'Rotherham United',
                 "Sheffield United FC": "Sheffield United",
                 'Sheffield Wednesday Football Club': 'Sheffield Wednesday',
       "Southampton Football Club": "Southampton", "Stoke City Football Club": "Stoke City",
       "Sunderland AFC": "Sunderland",
       "Swansea City Association Football Club": "Swansea City",
       "Tottenham Hotspur Football Club": "Tottenham Hotspur",
        'Queens Park Rangers Football Club': 'Queens Park Rangers',
       "Watford Football Club": "Watford", "West Bromwich Albion Football Club": "West Bromwich Albion",
       "West Ham United Football Club": "West Ham United",
        'Wigan Athletic Football Club': 'Wigan Athletic',
       "Wolverhampton Wanderers Football Club": "Wolverhampton",
        'Wycombe Wanderers FC': 'Wycombe Wanderers',
       }

Italy_sofascore = {'Atalanta Bergamasca Calcio': 'Atalanta', 'Benevento Calcio': 'Benevento',
         'Bologna Football Club 1909': 'Bologna', 'Brescia Calcio': 'Brescia',
         'Cagliari Calcio': 'Cagliari', 'Associazione Calcio ChievoVerona': 'ChievoVerona',
         'FC Crotone': 'Crotone',
         'Empoli Football Club': 'Empoli',
         'ACF Fiorentina': 'Fiorentina', 'Frosinone Calcio': 'Frosinone',
         'Genoa Football Club': 'Genoa',
         'Societa Sportiva Lazio': 'Lazio', 'Unione Sportiva Lecce': 'Lecce',
         'Football Club Internazionale Milano':  'Inter', 'Juventus Football Club': 'Juventus',
         'Associazione Calcio Milan': 'Milan', 'Sportiva Calcio Napoli': 'Napoli',
         'Parma Calcio 1913': 'Parma',
         'Associazione Sportiva Roma': 'Roma', 'Unione Sportiva Salernitana 1919': 'Salernitana',
         'Unione Calcio Sampdoria': 'Sampdoria',
         'Unione Sportiva Sassuolo Calcio': 'Sassuolo', 'Societa Polisportiva Ars et Labor': 'SPAL',
         'Spezia Calcio': 'Spezia',
         'Torino Football Club': 'Torino', 'Hellas Verona FC': 'Hellas Verona',
         'Udinese Calcio SpA': 'Udinese',
         'Venezia Football Club': 'Venezia'
         }

Spain_sofascore = {
    'Deportivo Alaves': 'Deportivo Alavés',
    'Club Atletico de Madrid': 'Atlético Madrid',
    'Futbol Club Barcelona': 'Barcelona',
    'Real Betis Balompie': 'Real Betis Balompié',
    'Athletic Club Bilbao': 'Athletic Club',
    'Cadiz Club de Futbol': 'Cádiz CF',
    'Real Club Celta de Vigo': 'Celta Vigo',
    'Sociedad Deportiva Eibar': 'Eibar',
    'Elche Club de Futbol': 'Elche CF',
    'Reial Club Deportiu Espanyol de Barcelona': 'Espanyol',
    'Getafe Club de Futbol': 'Getafe CF',
    'Girona Futbol Club': 'Girona FC',
    'Granada Club de Futbol': 'Granada',
    'Sociedad Deportiva Huesca': 'Huesca',
    'Club Deportivo Leganes': 'Leganés',
    'Levante Union Deportiva': 'Levante UD',
    'Real Madrid Club de Futbol': 'Real Madrid',
    'Real Club Deportivo Mallorca': 'RCD Mallorca',
    'Club Atletico Osasuna': 'Osasuna',
    'Sevilla Futbol Club': 'Sevilla',
    'Real Sociedad de Futbol': 'Real Sociedad',
    'Real Valladolid Club de Futbol': 'Real Valladolid',
    'Rayo Vallecano de Madrid': 'Rayo Vallecano',
    'Valencia Club de Futbol': 'Valencia',
    'Villarreal Club de Futbol': 'Villarreal'
}


Germany_sofascore = {
    'Fussball-Club Augsburg 1907': 'FC Augsburg',
    'Deutscher Sport-Club Arminia Bielefeld': 'Arminia Bielefeld',
    '1. FC Union Berlin': '1. FC Union Berlin',
    'Verein fur Leibesubungen Bochum 1848': 'VfL Bochum',
    'Ballspielverein Borussia 09 Dortmund': 'Borussia Dortmund',
    'Dusseldorfer Turn- und Sportverein Fortuna 1895': 'Fortuna Düsseldorf',
    'Eintracht Frankfurt': 'Eintracht Frankfurt',
    'Freiburger Fussball-Club': 'SC Freiburg',
    'Spielvereinigung Greuther Furth': 'SpVgg Greuther Fürth',
    'Hannoverscher Sportverein von 1896': 'Hannover 96',
    'Hertha Berliner Sport-Club': 'Hertha BSC',
    'Turn- und Sportgemeinschaft 1899 Hoffenheim': '1899 Hoffenheim',
    '1. Fussball Club Koln 01/07 e. V.': '1. FC Köln',
    'Bayer 04 Leverkusen Fusball GmbH': 'Bayer 04 Leverkusen',
    '1. Fussball- und Sport-Verein Mainz 05': '1. FSV Mainz 05',
    'Borussia Verein fur Leibesubungen 1900': "Borussia M'gladbach",
    'Fussball-Club Bayern Munchen': 'Bayern München',
    '1. Fussball-Club Nurnberg Verein fur Leibesubungen': '1. FC Nürnberg',
    'Sport-Club Paderborn 07': 'SC Paderborn 07',
    'RasenBallsport Leipzig': 'RB Leipzig',
    'Fussballclub Gelsenkirchen-Schalke 04': 'FC Schalke 04',
    'VfB Stuttgart': 'VfB Stuttgart',
    'Sportverein Werder Bremen von 1899': 'Werder Bremen',
    'Verein fur Leibesubungen Wolfsburg-Fussball': 'VfL Wolfsburg'
}

France_sofascore = {
    'AS Monaco FC': 'AS Monaco',
    'Amiens Sporting Club': 'Amiens SC',
    'Angers Sporting Club': 'Angers',
    'Football Club des Girondins de Bordeaux': 'Bordeaux',
    'Stade Malherbe Caen': 'Caen',
    'Clermont Foot 63': 'Clermont Foot 63',
    "Dijon Football Cote-d'Or": 'Dijon',
    'En Avant de Guingamp': 'Guingamp',
    'LOSC Lille Metropole': 'Lille OSC',
    'Football Club Lorient-Bretagne Sud': 'Lorient',
    'Football Club de Metz': 'Metz',
    'Montpellier Herault Sport Club': 'Montpellier',
    'Olympique Gymnaste Club Nice': 'OGC Nice',
    'Olympique Lyonnais': 'Olympique Lyonnais',
    'Olympique de Marseille': 'Olympique de Marseille',
    'Football Club de Nantes': 'FC Nantes',
    'Nimes Olympique Football Club': 'Nîmes Olympique',
    'Paris Saint-Germain Football Club': 'Paris Saint-Germain',
    'Racing Club de Lens': 'RC Lens',
    'Racing Club de Strasbourg': 'RC Strasbourg',
    'AS Saint-Etienne': 'Saint-Étienne',
    'Toulouse Football Club': 'Toulouse',
    'Stade Brestois 29': 'Stade Brestois 29',
    'Stade Rennais Football Club': 'Stade Rennais',
    'Stade de Reims': 'Stade de Reims',
    'Esperance Sportive Troyes Aube Champagne': 'Troyes'
}